### PR TITLE
Tests: Skip failing tests on windows

### LINKED ISSUE #8176: Pipeline: Add windows "self-hosted" pipeline equivalent
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

The current Windows PR CI pipeline build the toolchain, but does not execute any tests.  In order to ensure we don't regress on windows, it would be ideal to execute the tests on Windows.

However, the tests on Windows currently fail (See #8121).  In order to gain confidence, we should add an Windows Self-hosted CI pipeline before enabling tests on the the current [**Swift Test Windows Platform** Pipeline](https://ci-external.swift.org/job/swiftpm-PR-windows/)

However, we should be able to demand the "Windows self-host PR CI pipeline" on-demand, to ensure we introduce passing test in the same PR as the enabling the pipeline itself.

### Expected behavior

- Can demand the "Windows Self-hosted CI pipeline" against a PR
- The "Windows self-hosted CI pipeline" becomes gating after the PR is merged or after some soak time

### Actual behavior

N/A

### Steps to reproduce

N/A

### Swift Package Manager version/commit hash

N/A

### Swift & OS version (output of `swift --version ; uname -a`)

N/A

### PR DESCRIPTION
**Pull request by bkhouri**
The Pipelines do not currently test on windows platform.  To get to a point where we can execute tests on windows, we will first disable the failing tests and later enable them as the pipeline is setup to ensure we do not regress in behaviour.

related to #8121
rdar://139977454

### Motivation:

In preparation for #8176 , disable failing Windows tests.

### Modifications:

Mark some tests as Skipped on Windows

Fixes #8176

### CODE REVIEW

File: Sources/_InternalTestSupport/XCTSkipHelpers.swift [hunk 1]
```diff
@@ -17,6 +17,18 @@ import XCTest
 import class Basics.AsyncProcess
 import struct TSCBasic.StringError
 
+public func skipOnWindowsAsTestCurrentlyFails(because reason: String? = nil) throws {
+    #if os(Windows)
+    let failureCause: String
+    if reason == nil {
```
Comment (jakepetroules) [inline Sources/_InternalTestSupport/XCTSkipHelpers.swift:23]: The idiomatic way to do this in Swift would be:

```swift
if let reason {
    failureCause = " because \(reason.description)"
} else {
    failureCause = ""
}
```

(you want to avoid the force unwrap)

Comment (bkhouri) [reply Sources/_InternalTestSupport/XCTSkipHelpers.swift:23]: Thanks @jakepetroules .. I knew there was a more idiomatic way but my internet search failed me :)

File: Tests/BasicsTests/Environment/EnvironmentTests.swift [hunk 2]
```diff
@@ -99,10 +102,13 @@ final class EnvironmentTests: XCTestCase {
 
     /// Important: This test is inherently race-prone, if it is proven to be
     /// flaky, it should run in a singled threaded environment/removed entirely.
-    func test_current() {
+    func test_current() throws {
+        try skipOnWindowsAsTestCurrentlyFails(because: "ProcessInfo.processInfo.environment[\"PATH\"] return nil")
```
Comment (compnerd) [inline Tests/BasicsTests/Environment/EnvironmentTests.swift:106]: It should return `nil` as the variable is spelt `Path`.

Comment (bkhouri) [reply Tests/BasicsTests/Environment/EnvironmentTests.swift]: Thank you. The test has been updated to run and pass on Windows.

**Comment by bkhouri** [comment]
@swift-ci test self hosted window

**Comment by bkhouri** [comment]
@swift-ci test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

File: Utilities/build-using-self [hunk 3]
```diff
@@ -157,7 +157,7 @@ def main() -> None:
         swift_testing_arg= "--enable-swift-testing" if args.enable_swift_testing else ""
         xctest_arg= "--enable-xctest" if args.enable_swift_testing else ""
         call(
-            shlex.split(f"swift test --configuration {args.config} --parallel {swift_testing_arg} {xctest_arg}"),
+            shlex.split(f"swift test --configuration {args.config} --no-parallel {swift_testing_arg} {xctest_arg}"),
```
[the remark this answers is not in the document]
Comment (bkhouri) [reply Utilities/build-using-self]: done

File: Utilities/build-using-self [hunk 4]
```diff
@@ -166,7 +166,8 @@ def main() -> None:
         )
         call(
             shlex.split(
-                f"{swiftpm_bin_dir / 'swift-test'} --parallel",
+                f"{swiftpm_bin_dir / 'swift-test'} --no-parallel",
```
[the remark this answers is not in the document]
Comment (bkhouri) [reply Utilities/build-using-self]: done

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test self hosted windows

**Comment by bkhouri** [comment]
@swift-ci please test

**Comment by bkhouri** [comment]
@swift-ci please test windows

**Review by compnerd — APPROVED** [review]
This seems to be in a much worse state than I remember 🤔

**Comment by bkhouri** [comment]
Alot of the workspace tests might need updating the tests itself.    I just wanted to get a set of passing tests, to ensure we don't regress, and will work on re-enabling more tests.

**Review by dschaefer2 — APPROVED** [review]
