### PR TITLE
Display PID of other running SwiftPM processes

### LINKED ISSUE #8528: Display the process ID in the when running a Swift PM command that has a hold of the .build directory
### Description

As a software developer using Swift Package Manager, I would like the "lock message" to contain the Process ID that is locking a Swift PM action so that I can inspect  the process and make an informed decision if I want to terminate it or let it run to completion.

### Expected behavior

Swift PM has knowledge that another instance is currently using the `.build` directory. It would be ideal to include the process ID of that instance in the message

```
❯ swift build --disable-prefetching
Another instance of SwiftPM is already running using '/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/.build', waiting until that process has finished execution...
```

### Actual behavior

maybe something line 

```
❯ swift build --disable-prefetching
Another instance of SwiftPM (pID ######) is already running using '/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/.build', waiting until that process has finished execution...
```

### Steps to reproduce

1. Open a terminal, and run `swift test --no-parallel` (ensuring the build takes "time")
2. While the first command is running, in another terminal, execute `swift test --no-parallel`

### Swift Package Manager version/commit hash

Swift Package Manager - Swift 6.1.0

### Swift & OS version (output of `swift --version && uname -a`)

```
❯ uname -a
Darwin BKs-Work-M1Pro-MacBook-Pro-3.local 24.5.0 Darwin Kernel Version 24.5.0: Sun Apr 13 22:01:22 PDT 2025; root:xnu_development-11417.120.105.0.2~26/DEVELOPMENT_ARM64_T6000 arm64

❯ swift --version
Apple Swift version 6.1 (swift-6.1-RELEASE)
Target: arm64-apple-macosx15.0
```

### PR DESCRIPTION
**Pull request by louisunlimited**
Displays the PID of the other SwiftPM instance currently holding the lock

### Motivation:
- Fixes #8528 

When we try to run different SwiftPM processes we already see notes like 

```
Another instance of swiftPM is already running using '/Users/louissssss/swift-package-manager/.build', waiting until that process has finished execution...
```

I'll be nice to also have info about PID so I can choose to terminate it or wait for it to finish, so it might display smt like:
```
Another instance of SwiftPM (PID: 3404) is already running using '/Users/louissssss/swift-package-manager/.build', waiting until that process has finished execution...
```

### Modifications:

My approach was trying to write process id from the process that acquires the lock to the lock file and then let other processes read from it and get the pid.

### Result:

If another SwiftPM process is currently running, it now displays:
```
Another instance of SwiftPM (PID: 3404) is already running using '/Users/louissssss/swift-package-manager/.build', waiting until that process has finished execution...
```

### CODE REVIEW

File: Sources/CoreCommands/SwiftCommandState.swift [hunk 1]
```diff
@@ -1064,25 +1064,33 @@ public final class SwiftCommandState {
         // Try a non-blocking lock first so that we can inform the user about an already running SwiftPM.
         do {
             try workspaceLock.lock(type: .exclusive, blocking: false)
+            let pid = ProcessInfo.processInfo.processIdentifier
+            try String(pid).write(toFile: self.scratchDirectory.appending(".lock").pathString, atomically: true, encoding: .utf8)
         } catch ProcessLockError.unableToAquireLock(let errno) {
             if errno == EWOULDBLOCK {
+                let lockingPID = try? String(contentsOfFile: self.scratchDirectory.appending(".lock").pathString, encoding: .utf8)
+                let pidInfo = lockingPID.map { "(PID: \($0))" } ?? ""
```
Comment (jakepetroules) [inline Sources/CoreCommands/SwiftCommandState.swift:1072]: I'd add a space after the closing parenthesis, like so:

```swift
let pidInfo = lockingPID.map { "(PID: \($0)) " } ?? ""
```

...and then correspondingly remove the space after the `pifInfo` interpolation a few lines down, like so:

```swift
"Another instance of SwiftPM \(pidInfo)is already running using '\(self.scratchDirectory)', but this will be ignored since `--ignore-lock` has been passed"
```

...so that we don't end up with a double space between "SwiftPM" and "is" if we couldn't read the PID, since that would look out of place.

**Review by jakepetroules — CHANGES_REQUESTED** [review]

**Comment by jakepetroules** [comment]
Thanks for your PR, this is a nice little enhancement! Just had some minor formatting related-feedback.

File: Sources/CoreCommands/SwiftCommandState.swift [hunk 2]
```diff
@@ -1064,25 +1064,33 @@ public final class SwiftCommandState {
         // Try a non-blocking lock first so that we can inform the user about an already running SwiftPM.
         do {
             try workspaceLock.lock(type: .exclusive, blocking: false)
+            let pid = ProcessInfo.processInfo.processIdentifier
+            try String(pid).write(toFile: self.scratchDirectory.appending(".lock").pathString, atomically: true, encoding: .utf8)
```
Comment (plemarquand) [inline Sources/CoreCommands/SwiftCommandState.swift:1068]: nit: refactor out `self.scratchDirectory.appending(".lock").pathString` in to a variable

**Comment by louisunlimited** [comment]
Just did all the changes, one other thought: would it be better if we mark `String(pid).write(toFile: lockFile, atomically: true, encoding: .utf8)` with `try?` instead of `try` so this is not a critical throw and will not stop the program? I'd say as long as we can acquire the lock we should not interrupt normal execution.

**Comment by plemarquand** [comment]
@louisunlimited I think that's a good idea. It's a non-essential call and worst case the message just falls back to what we have today.

**Comment by louisunlimited** [comment]
> @louisunlimited I think that's a good idea. It's a non-essential call and worst case the message just falls back to what we have today.

Cool, just pushed the changes, lmk if you need me for anything else

**Review by jakepetroules — APPROVED** [review]

**Comment by plemarquand** [comment]
@swift-ci test

**Comment by johnbute** [comment]
Great pr Louis! I was working on the same thing too:

https://github.com/swiftlang/swift-package-manager/pull/8618

 If you want to take any changes from it to enhance yours please do :)

**Comment by louisunlimited** [comment]
@jakepetroules @plemarquand hey just wanna check in and see if there's anything I can do to help the Windows CI run?

**Comment by plemarquand** [comment]
@swift-ci please test windows
