### PR TITLE
[Traits] Fix traits omitting used package dependencies

### LINKED ISSUE #8398: [Traits] Used package dependency omitted when traits guard some target dependencies
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

The computation for trait-guarded dependencies did not consider differentiating between product target dependencies coming from the same package wherein one could be trait-guarded and the other could be enabled, causing it to preemptively omit the package dependency entirely if it encounters a trait guard.

### Expected behavior

SwiftPM should ensure that it computes the target dependencies that are being trait-guarded, and assure that a dependency is only guarded if every instance of it appears to be trait-guarded. Otherwise, it should include this dependency if it's being used.

### Actual behavior

SwiftPM preemptively omits a package dependency it believes to be trait-guarded when there are existing target dependencies that aren't guarded.

### Steps to reproduce

Download the attached example project and run a `swift build` in the `root` directory; note that it errors out with:

```
[0/1] Planning build
Building for debugging...
[0/4] Write swift-version--58304C5D6DBC2206.txt
error: emit-module command failed with exit code 1 (use -v to see invocation)
[2/6] Emitting module root
<unknown>:0: error: missing required module 'bestlowest'
[3/6] Compiling root main.swift
<unknown>:0: error: missing required module 'bestlowest'
```

[packtest.zip](https://github.com/user-attachments/files/19374949/packtest.zip)

### Swift Package Manager version/commit hash

_No response_

### Swift & OS version (output of `swift --version ; uname -a`)

_No response_

### PR DESCRIPTION
**Pull request by bripeticca**
Fixes #8398 

Used package dependencies of a manifest were considered trait-guarded if a target dependency in the manifest:

1. used a product from said package and
2. was trait-guarded

regardless as to whether the same package dependency was used elsewhere (whether in the same target or another in the same manifest) and was not guarded by traits.

This change ensures that this is considered when doing the calculations for package dependencies that should be omitted if *every* target dependency that uses said package dependency is guarded.

### CODE REVIEW

**Comment by bripeticca** [comment]
@swift-ci please test

File: Sources/PackageModel/Manifest/Manifest.swift [hunk 1]
```diff
@@ -877,17 +865,27 @@ extension Manifest {
...
-            let traitGuardedTargetDependencies = target.dependencies.filter {
-                !($0.condition?.traits?.isEmpty ?? true)
-            }
-            traitGuardedTargetDependencies.forEach {
-                guard let package = lowercasedKeys ? $0.package?.lowercased() : $0.package else { return }
-                depMap[package, default: [:]][target.name, default: []].formUnion($0.condition?.traits ?? [])
-            }
+
+    /// Computes the list of target dependencies per target that are guarded by traits.
+    /// A  target dependency is considered potentially trait-guarded if it defines a condition wherein there exists a list of traits.
```
Comment (MaxDesiatov) [inline Sources/PackageModel/Manifest/Manifest.swift:870]: Formatting nit. Also, could the doc string contain a more detailed description for what the return type representst
```suggestion
    /// A target dependency is considered potentially trait-guarded if it defines a condition wherein there exists a list of traits.
```

File: Sources/PackageModel/Manifest/Manifest.swift [hunk 2]
```diff
@@ -877,17 +865,27 @@ extension Manifest {
...
+
+            traitGuardedTargetDependencies.forEach({
+                guard let package = lowercasedKeys ? $0.key.package?.lowercased() : $0.key.package else { return }
+                depMap[package, default: []].append($0.key)
+            })
+        }
+    }
+
+    /// Computes the list of target dependencies that are guarded by traits for given target.
+    /// A  target dependency is considered potentially trait-guarded if it defines a condition wherein there exists a list of traits.
```
Comment (MaxDesiatov) [inline Sources/PackageModel/Manifest/Manifest.swift:883]: Docstring nit, ditto
```suggestion
    /// A target dependency is considered potentially trait-guarded if it defines a condition wherein there exists a list of traits.
```

File: Sources/PackageModel/Manifest/Manifest.swift [hunk 3]
```diff
@@ -877,17 +865,27 @@ extension Manifest {
...
+    public func traitGuardedTargetDependencies(lowercasedKeys: Bool = false, for target: TargetDescription) -> [TargetDescription.Dependency: Set<String>] {
```
Comment (MaxDesiatov) [inline Sources/PackageModel/Manifest/Manifest.swift:884]: formatting nit for better readability on non-ultrawide screens
```suggestion
    public func traitGuardedTargetDependencies(
        lowercasedKeys: Bool = false,
        for target: TargetDescription
    ) -> [TargetDescription.Dependency: Set<String>] {
```

**Comment by bripeticca** [comment]
@swift-ci please test

File: Sources/PackageModel/Manifest/Manifest.swift [hunk 4]
```diff
@@ -877,20 +869,45 @@ extension Manifest {
...
-            }
+    /// Computes the list of target dependencies per target that are guarded by traits.
+    /// A target dependency is considered potentially trait-guarded if it defines a condition wherein there exists a
+    /// list of traits.
+    /// - Parameters:
+    ///    - lowercasedKeys: A flag that determines whether the keys in the resulting dictionary are lowercased.
+    /// - Returns: A dictionary that maps the name of a `TargetDescription` to a list of its dependencies that are
+    /// guarded by traits.
+    public func traitGuardedTargetDependencies(lowercasedKeys: Bool = false)
+        -> [String: [TargetDescription.Dependency]]
```
Comment (MaxDesiatov) [inline Sources/PackageModel/Manifest/Manifest.swift:880]: The convention (IIRC respected by SwiftFormat) is to keep the arrow on the same line as a closing paren. If splitting lines is needed, parameters are put on separate lines.

```suggestion
    public func traitGuardedTargetDependencies(
        lowercasedKeys: Bool = false
    ) -> [String: [TargetDescription.Dependency]]
```

**Comment by bripeticca** [comment]
@swift-ci please test

**Comment by bripeticca** [comment]
@swift-ci please test windows

**Comment by bripeticca** [comment]
@swift-ci please test windows

**Comment by MaxDesiatov** [comment]
Good to merge?
