### PR TITLE
[Traits] Re-enable no unused dependencies assertion in `TraitTests.swift`

### LINKED ISSUE #8131: TraitsTests fails when running in 6.1 toolchain
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Some of the `TraitsTests` are failing when running against 6.1 toolchain. This is preventing the self-hosted macOS pipeline to upgrade from 5.9 top 6.1 toolchain

### Expected behavior

All tests in `TraitTests` should pass.  More specifically,  the  `XCTAssertFalse(stderr.contains("warning:"))` in each test should not be wrapped in a `XCTAssertThrowsError()` and should not be commented out. This part of the test may have been updated to allow the test to pass with the 6.x toolchain.
```
                XCTAssertFalse(stderr.contains("warning:"))
```

### Actual behavior

```
❯ git rev-parse HEAD                                 
cb829d83d016beb6607fde42136a079c37297d90

❯ swift build --build-tests
<...SNI...>
[48/48] Linking SwiftPMPackageTests
Build complete! (18.86s)

❯ swift test --filter "TraitTest*"
[1/1] Planning build
Building for debugging...
[2/2] Write swift-version--2A2C2CE82E0D52A1.txt
Build complete! (4.51s)
Test Suite 'Selected tests' started at 2024-11-21 09:01:08.654.
Test Suite 'SwiftPMPackageTests.xctest' started at 2024-11-21 09:01:08.656.
Test Suite 'TraitTests' started at 2024-11-21 09:01:08.656.
Test Case '-[FunctionalTests.TraitTests testTests_whenAllTraitsEnabled_andDefaultTraitsDisabled]' started.
Test Case '-[FunctionalTests.TraitTests testTests_whenAllTraitsEnabled_andDefaultTraitsDisabled]' passed (72.768 seconds).
Test Case '-[FunctionalTests.TraitTests testTests_whenNoFlagPassed]' started.
Test Case '-[FunctionalTests.TraitTests testTests_whenNoFlagPassed]' passed (12.702 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_dumpPackage]' started.
Test Case '-[FunctionalTests.TraitTests testTraits_dumpPackage]' passed (4.528 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenAllTraitsEnabled_andDefaultTraitsDisabled]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:161: error: -[FunctionalTests.TraitTests testTraits_whenAllTraitsEnabled_andDefaultTraitsDisabled] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenAllTraitsEnabled_andDefaultTraitsDisabled]' failed (11.622 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenAllTraitsEnabled]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:136: error: -[FunctionalTests.TraitTests testTraits_whenAllTraitsEnabled] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenAllTraitsEnabled]' failed (11.261 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenDefaultTraitsDisabled]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:105: error: -[FunctionalTests.TraitTests testTraits_whenDefaultTraitsDisabled] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenDefaultTraitsDisabled]' failed (9.884 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenIndividualTraitsEnabled_andDefaultTraitsDisabled]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:119: error: -[FunctionalTests.TraitTests testTraits_whenIndividualTraitsEnabled_andDefaultTraitsDisabled] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenIndividualTraitsEnabled_andDefaultTraitsDisabled]' failed (10.647 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenIndividualTraitsEnabled_andDefaultTraits]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:84: error: -[FunctionalTests.TraitTests testTraits_whenIndividualTraitsEnabled_andDefaultTraits] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenIndividualTraitsEnabled_andDefaultTraits]' failed (10.932 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenNoFlagPassed]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:24: error: -[FunctionalTests.TraitTests testTraits_whenNoFlagPassed] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenNoFlagPassed]' failed (10.593 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenTraitUnification_whenSecondTraitNotEnabled]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:64: error: -[FunctionalTests.TraitTests testTraits_whenTraitUnification_whenSecondTraitNotEnabled] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenTraitUnification_whenSecondTraitNotEnabled]' failed (10.968 seconds).
Test Case '-[FunctionalTests.TraitTests testTraits_whenTraitUnification]' started.
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Tests/FunctionalTests/TraitTests.swift:42: error: -[FunctionalTests.TraitTests testTraits_whenTraitUnification] : XCTAssertFalse failed
Test Case '-[FunctionalTests.TraitTests testTraits_whenTraitUnification]' failed (10.950 seconds).
Test Suite 'TraitTests' failed at 2024-11-21 09:04:05.511.
         Executed 11 tests, with 8 failures (0 unexpected) in 176.855 (176.855) seconds
Test Suite 'SwiftPMPackageTests.xctest' failed at 2024-11-21 09:04:05.511.
         Executed 11 tests, with 8 failures (0 unexpected) in 176.855 (176.855) seconds
Test Suite 'Selected tests' failed at 2024-11-21 09:04:05.511.
         Executed 11 tests, with 8 failures (0 unexpected) in 176.855 (176.857) seconds
◇ Test run started.
↳ Testing Library Version: 107
↳ Target Platform: arm64e-apple-macos14.0
✔ Test run with 0 tests passed after 0.001 seconds.
```

### Steps to reproduce

Ensure the`XCTAssertFalse(stderr.contains("warning:"))` in the tests are not wrapped in a `XCTAssertThrowsError()` call, then

```
git checkout cb829d83d016beb6607fde42136a079c37297d90
swift test --filter "TraitTests"
```

### Swift Package Manager version/commit hash

cb829d83d016beb6607fde42136a079c37297d90

### Swift & OS version (output of `swift --version ; uname -a`)

```
❯ swiftly list
Installed release toolchains
----------------------------
<... SNIP ...>
Installed snapshot toolchains
-----------------------------
main-snapshot-2024-11-16 (in use)


❯ swift --version
warning: Unable to locate libSwiftScan. Fallback to `swift-frontend` dependency scanner invocation.
Apple Swift version 6.1-dev (LLVM c7635515f932833, Swift dbf388c0a58df0e)
Target: arm64-apple-macosx15.0

❯ uname -a
Darwin BKs-Work-M1Pro-MacBook-Pro-2.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Oct 25 20:33:26 PDT 2024; root:xnu_development-11215.60.400.0.1~11/DEVELOPMENT_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by bripeticca**
Fixes #8131 

Previously this check was disabled since it introduced failures when testing with the 6.1 toolchain - due to the introduction of traits in resolution (#8205) and additional behaviour from the experimental prune dependencies flag, this check should now pass as expected.

### Modifications:

Re-enabled the `XCTAssertFalse(stderr.contains("warning:"))` check in the `TraitTests` where necessary and propagated the `pruneDependencies` flag to the `ManifestLoader` init in areas it was previously missing to assure no warnings would be generated upon omitting them. Also re-added the enabled traits parameter done during a computation for required dependencies when creating the package builders in `ModulesGraph+Loading.swift`.

### Result:

This check shouldn't fail anymore.

### CODE REVIEW

**Comment by bripeticca** [comment]
@swift-ci please test

**Comment by bripeticca** [comment]
@swift-ci please test

**Comment by bripeticca** [comment]
@swift-ci please smoke test linux

**Comment by bripeticca** [comment]
@swift-ci please smoke test linux

**Comment by bripeticca** [comment]
@swift-ci please smoke test Linux

**Comment by bripeticca** [comment]
@swift-ci please test windows

**Comment by bripeticca** [comment]
@swift-ci please smoke test linux

File: Sources/PackageModel/Manifest/Manifest.swift [hunk 1]
```diff
@@ -181,8 +181,19 @@ public final class Manifest: Sendable {
...
+    /// that dependency being used, then that dependency is not considered trait-guarded.
+    ///
+    /// For example:
+    ///
+    /// Consider a package dependency `Bar` that is present in the manifest, and the manifest defines the following target:
+    /// `TargetDescription(name: "Baz", dependencies: [.product(name: "Bar", condition: .init(traits: ["Trait1"])]`
+    ///
+    /// If we set the `enabledTraits` to be `["Trait1"]`, then the list of dependencies guarded by traits would be `[]`.
+    /// Otherwise, if `enabledTraits` were `nil`, then the dependencies guarded by traits would be `["Bar"]`.
+    public func dependenciesTraitGuarded(withEnabledTraits enabledTraits: Set<String>?, enableAllTraits: Bool = false) -> [PackageDependency] {
```
Comment (MaxDesiatov) [inline Sources/PackageModel/Manifest/Manifest.swift:196]: Formatting nit for readability on non-ultrawide screens.
```suggestion
    public func dependenciesTraitGuarded(
        withEnabledTraits enabledTraits: Set<String>?,
        enableAllTraits: Bool = false
    ) -> [PackageDependency] {
```

File: Sources/Workspace/Workspace+Manifests.swift [hunk 2]
```diff
@@ -656,7 +656,7 @@ extension Workspace {
         let successorNodes: (KeyedPair<GraphLoadingNode, PackageIdentity>) async throws -> [KeyedPair<GraphLoadingNode, PackageIdentity>] = { node in
             // optimization: preload manifest we know about in parallel
             let dependenciesRequired = try node.item.manifest.dependenciesRequired(for: node.item.productFilter, node.item.enabledTraits)
-            let dependenciesGuarded = node.item.manifest.dependenciesGuarded(by: node.item.enabledTraits)
+            let dependenciesGuarded = node.item.manifest.dependenciesTraitGuarded(withEnabledTraits: node.item.enabledTraits)
```
Comment (MaxDesiatov) [inline Sources/Workspace/Workspace+Manifests.swift:659]:
```suggestion
            let dependenciesGuarded = node.item.manifest.dependenciesTraitGuarded(
                withEnabledTraits: node.item.enabledTraits
            )
```

File: Tests/FunctionalTests/TraitTests.swift [hunk 3]
```diff
@@ -18,10 +18,10 @@ import XCTest
 final class TraitTests: XCTestCase {
     func testTraits_whenNoFlagPassed() async throws {
         try await fixture(name: "Traits") { fixturePath in
-            let (stdout, _) = try await executeSwiftRun(fixturePath.appending("Example"), "Example", extraArgs: ["--experimental-prune-unused-dependencies"])
+            let (stdout, stderr) = try await executeSwiftRun(fixturePath.appending("Example"), "Example", extraArgs: ["--experimental-prune-unused-dependencies"])
```
Comment (MaxDesiatov) [inline Tests/FunctionalTests/TraitTests.swift:21]: Creating PR suggestions for every long line in this file is tedious, but I'd expect a SwiftFormat pass on this file to handle all long lines.

**Review by MaxDesiatov — APPROVED** [review]

**Comment by bripeticca** [comment]
@swift-ci please test windows
