### PR TITLE
Prevent non-targets from depending on test targets

### LINKED ISSUE #8478: Prevent non-test targets from depending on test targets
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [x] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

Currently, a developer can have a non-test target depend on an test target, and Swift PM will happily try to compile, and fail

### Expected behavior

An appropriate error message stating a target cannot depend on a test target

### Actual behavior

```
❯ swift build --package-path Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget
[1/1] Planning build
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/Sources/DependencyTargetDependsOnTestTarget/DependencyTargetDependsOnTestTarget.swift:4:8: error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
2 | // https://docs.swift.org/swift-book
3 |
4 | import DependencyTargetDependsOnTestTargetTests
  |        `- error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
5 |
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/Sources/DependencyTargetDependsOnTestTarget/DependencyTargetDependsOnTestTarget.swift:4:8: error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
2 | // https://docs.swift.org/swift-book
3 |
4 | import DependencyTargetDependsOnTestTargetTests
  |        `- error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
5 |
```

### Steps to reproduce

1. extract the attached [repro.tgz](https://github.com/user-attachments/files/19692504/repro.tgz)
2. `swift build --package-path <path/to/extracted/repo>`

### Swift Package Manager version/commit hash

_No response_

### Swift & OS version (output of `swift --version ; uname -a`)
```
❯ uname -a                                                                                       
Darwin BKs-Work-M1Pro-MacBook-Pro-2.local 24.4.0 Darwin Kernel Version 24.4.0: Tue Mar 11 22:26:20 PDT 2025; root:xnu_development-11417.101.12~4/DEVELOPMENT_ARM64_T6000 arm64

❯ swift --version           
Apple Swift version 6.1 (swift-6.1-RELEASE)
Target: arm64-apple-macosx15.0
```

### PR DESCRIPTION
**Pull request by johnbute**
Prevent non-targets from depending on test targets

### Motivation:

Fix for rdar://149007214 
Currently, only test targets are allowed to have dependencies on other test targets.

### Modifications:

Simply checked for each non-test target, if their dependency is of type test. If it is, throw an error.

### Result:

Swift package manager will give an error explaining that only testTargets can depend on other testTargets

Fixes #8478

### CODE REVIEW

File: Sources/PackageLoading/PackageBuilder.swift [hunk 1]
```diff
@@ -949,6 +949,19 @@ public final class PackageBuilder {
                 }
         }
 
+        // Ensure non-test targets do not depend on test targets.
+        // Only test targets are allowed to have dependencies on other test targets.
+        if !potentialModule.isTest {
+            for dependency in dependencies {
+                if let depTarget = dependency.module, depTarget.type == .test {
+                    self.observabilityScope.emit(.invalidDependencyOnTestTarget(
+                        dependency: dependency.name,
```
Comment (bkhouri) [inline Sources/PackageLoading/PackageBuilder.swift:958]: suggestion (non-blocking): consider passing the entire structure to the `dependency` and `targetName` argument to allow the `invalidDependencyOnTestTarget` to have additional control on possibly using "other" information.

File: Tests/PackageGraphTests/ModulesGraphTests.swift [hunk 2]
```diff
@@ -410,6 +410,72 @@ final class ModulesGraphTests: XCTestCase {
...
+            manifests: [
+                Manifest.createRootManifest(
+                    displayName: "Foo",
+                    path: "/Foo",
+                    toolsVersion: .v6_0,
+                    products: [
+                        ProductDescription(name: "Foo", type: .library(.automatic), targets: ["FooTest"]),
+                    ],
+                    targets: [
+                        TargetDescription(name: "Foo", dependencies: ["FooTest"]),
```
Comment (bkhouri) [inline Tests/PackageGraphTests/ModulesGraphTests.swift:433]: praise: thanks for adding the automated tests, but can we add an automated test for the following cases

- binaryTarget depends on Test target
- libraryTarget depends on test Target
- executableTarget depends on test target
- plugin target depends on test target
- are there any other targets types?

File: Sources/PackageLoading/PackageBuilder.swift (hunk 1 above)
Comment (johnbute) [reply Sources/PackageLoading/PackageBuilder.swift]: Done partially, I cannot pass the entire target structure since the target is of type `PotentialModule` and not `Module`

File: Tests/PackageGraphTests/ModulesGraphTests.swift (hunk 2 above)
Comment (johnbute) [reply Tests/PackageGraphTests/ModulesGraphTests.swift:433]: I have done test cases for library, executable, plugins, and macros, but I believe binaryTargets cannot have any dependencies.

File: Sources/PackageLoading/ManifestLoader+Validation.swift [hunk 3]
```diff
@@ -309,6 +309,12 @@ extension Basics.Diagnostic {
         return .error("\(messagePrefix) in dependencies of target '\(targetName)'; valid packages are: \(validPackages.map{ "\($0.descriptionForValidation)" }.joined(separator: ", "))")
     }
 
+    static func invalidDependencyOnTestTarget(dependency: Module.Dependency, targetName: String) -> Self {
```
Comment (cmcgee1024) [inline Sources/PackageLoading/ManifestLoader+Validation.swift:312]: question: How best to manage packages out there that might be doing this already? This might need to be an opt-in feature either by the `swift-tools` comment at the top of the package so that packages can adopt the stricter checking.

Comment (johnbute) [reply Sources/PackageLoading/ManifestLoader+Validation.swift:312]: Currently, if you do this, you get the following error and your package does not build:



`❯ swift build --package-path Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget
[1/1] Planning build
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/Sources/DependencyTargetDependsOnTestTarget/DependencyTargetDependsOnTestTarget.swift:4:8: error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
2 | // https://docs.swift.org/swift-book
3 |
4 | import DependencyTargetDependsOnTestTargetTests
  |        `- error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
5 |
/Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/Sources/DependencyTargetDependsOnTestTarget/DependencyTargetDependsOnTestTarget.swift:4:8: error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
2 | // https://docs.swift.org/swift-book
3 |
4 | import DependencyTargetDependsOnTestTargetTests
  |        `- error: compiling for macOS 10.13, but module 'DependencyTargetDependsOnTestTargetTests' has a minimum deployment target of macOS 14.0: /Users/bkhouri/Documents/git/public/swiftlang/swift-package-manager/Fixtures/Miscellaneous/DependencyTargetDependsOnTestTarget/.build/arm64-apple-macosx/debug/Modules/DependencyTargetDependsOnTestTargetTests.swiftmodule
5 |`

**Comment by johnbute** [comment]
@swift-ci please test

**Comment by johnbute** [comment]
@swift-ci test macOS

**Comment by johnbute** [comment]
@swift-ci test windows

File: Sources/PackageLoading/ManifestLoader+Validation.swift (hunk 3 above)
Comment (bkhouri) [reply Sources/PackageLoading/ManifestLoader+Validation.swift:312]: If package are already doing this, they need to be updated as it does not make sense to have a non-test target depend on a test target.

Maybe we should add something to the "change log" as a possibly breaking change.

**Review by bkhouri — APPROVED** [review]

**Comment by johnbute** [comment]
@swift-ci Please smoke test macOS platform

**Comment by johnbute** [comment]
@swift-ci please test macos
